language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
before_install:
  - pip install --upgrade pip
  - pip install poetry
install:
  - poetry install
script:
  - if [[ $TRAVIS_PYTHON_VERSION != 3.5 ]]; then poetry run black --check .; fi
  - poetry run isort **/*.py
  - poetry run pytest tests --cov=immutabledict
after_success:
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - pip install --upgrade pip
  - pip install poetry
  - poetry config pypi-token.pypi $PYPI_TOKEN
  - poetry build

jobs:
  include:
    - stage: deploy
      script: poetry publish
      python: "3.8"
      skip_cleanup: true
      on:
        tags: true