language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
before_install:
  - pip install poetry
install:
  - poetry install
script:
  - if [[ $TRAVIS_PYTHON_VERSION != 3.5 ]]; then poetry run black --check; fi
  - poetry run isort **/*.py
  - poetry run pytest tests --cov=immutabledict
after_success:
  - codecov