[tool.poetry]
name = "immutabledict"
version = "0.1.0"
description = "Immutable wrapper around dictionaries"
authors = ["Corentin Garcia <corenting@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.5"

[tool.poetry.dev-dependencies]
black = {version = "^19.10b0", python = "^3.6"}
pytest = "^5.3"
isort = "^4.3.21"
pytest-cov = "^2.8.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
