name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ci:
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        run: pip install poetry
      - name: Setup environment
        run: poetry install
      - name: Style
        if: ${{ matrix.python-version == '3.9' }}  # to run only once
        run: make style
      - name: Test
        run: make test
      - name: Codecov
        uses: codecov/codecov-action@v1
        if: ${{ matrix.python-version == '3.9' }}  # to run only once
      - name: Publish on PyPI
        if: ${{ startsWith('refs/tags/v', github.ref) && matrix.python-version == '3.9' }}
        run: >
          poetry config pypi-token.pypi $PYPI_TOKEN
          poetry build
          poetry publish
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
